name: Sync Fork

on:
  push:
  schedule:
    - cron: '0 7 * * *'

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Fork with Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: google-gemini/gemini-cli
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 恢复本地 workflow 目录内容
        run: |
          git checkout HEAD -- .github/workflows || true
