# .github/workflows/sync.yml
name: Sync Fork

on:
  push:
  schedule:
    - cron: '0 7 * * *'
    
    
permissions: # <-- 在这里添加权限配置
    contents: write # 允许写入代码（通常是默认的）
    actions: write
    pull-requests: write # 如果 Action 需要创建 PR，也需要此权限

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 备份 workflows 目录
        run: |
          cp -r .github/workflows /tmp/workflows_backup || true

      - name: Sync Fork with Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: google-gemini/gemini-cli
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 恢复原 workflows 目录
        run: |
          rm -rf .github/workflows
          mv /tmp/workflows_backup .github/workflows || true
          
